//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int AuditTrailLogID { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_Log { get; set; }
        public string Log_History { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Session_ID { get; set; }
        public Nullable<int> ClientProgress_ID { get; set; }
        public Nullable<int> Sale_ID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual ClientProgress ClientProgress { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
    }
}
