//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int Availability_ID { get; set; }
        public int TimeSlot_ID { get; set; }
        public int Date_ID { get; set; }
        public Nullable<int> Trainee_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Practitioner_ID { get; set; }
        public Nullable<int> Trainer_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Date Date { get; set; }
        public virtual Practitioner Practitioner { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
