//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.AuditTrails = new HashSet<AuditTrail>();
            this.Sessions = new HashSet<Session>();
            this.UserDaySlots = new HashSet<UserDaySlot>();
        }
    
        public int Booking_ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public System.TimeSpan End_Time { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> BookingStatus_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Service_ID { get; set; }
        public Nullable<int> Package_ID { get; set; }
        public Nullable<int> SessionType_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
        public virtual BookingStatu BookingStatu { get; set; }
        public virtual Client Client { get; set; }
        public virtual Package Package { get; set; }
        public virtual Service Service { get; set; }
        public virtual SessionType SessionType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDaySlot> UserDaySlots { get; set; }
    }
}
