//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Availabilities = new HashSet<Availability>();
            this.Bookings = new HashSet<Booking>();
            this.QuestionAnswers = new HashSet<QuestionAnswer>();
            this.QuestionnaireFeedbacks = new HashSet<QuestionnaireFeedback>();
            this.Ratings = new HashSet<Rating>();
            this.Results = new HashSet<Result>();
            this.Sales = new HashSet<Sale>();
            this.Sessions = new HashSet<Session>();
            this.Tasks = new HashSet<Task>();
            this.UserQuestionnaires = new HashSet<UserQuestionnaire>();
        }
    
        public int Client_ID { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string ID_Number { get; set; }
        public string Passport_Number { get; set; }
        public string Profile_Picture { get; set; }
        public string Email_Address { get; set; }
        public string Contact_Number { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public bool Client_Status { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> ClientType_ID { get; set; }
        public Nullable<int> Practitioner_ID { get; set; }
        public Nullable<int> ClientProgress_ID { get; set; }
        public Nullable<int> ClientStatus_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Availability> Availabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ClientProgress ClientProgress { get; set; }
        public virtual ClientStatu ClientStatu { get; set; }
        public virtual ClientType ClientType { get; set; }
        public virtual Practitioner Practitioner { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnaireFeedback> QuestionnaireFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserQuestionnaire> UserQuestionnaires { get; set; }
    }
}
