//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateSlot
    {
        public int DaySlot_ID { get; set; }
        public int TimeSlot_ID { get; set; }
        public int Date_ID { get; set; }
    
        public virtual Date Date { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
