//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Document_ID { get; set; }
        public byte[] Name { get; set; }
        public string Document1 { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> DocumentType_ID { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual User User { get; set; }
    }
}
