//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FICSEntities : DbContext
    {
        public FICSEntities()
            : base("name=FICSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddRemove> AddRemoves { get; set; }
        public virtual DbSet<AuditTrail> AuditTrails { get; set; }
        public virtual DbSet<Availability> Availabilities { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingStatu> BookingStatus { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientProgress> ClientProgresses { get; set; }
        public virtual DbSet<ClientStatu> ClientStatus { get; set; }
        public virtual DbSet<ClientType> ClientTypes { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<DateSlot> DateSlots { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackageService> PackageServices { get; set; }
        public virtual DbSet<PackageType> PackageTypes { get; set; }
        public virtual DbSet<Practitioner> Practitioners { get; set; }
        public virtual DbSet<PractitionerStatu> PractitionerStatus { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<QuestionAnswer> QuestionAnswers { get; set; }
        public virtual DbSet<QuestionBankType> QuestionBankTypes { get; set; }
        public virtual DbSet<QuestionDetail> QuestionDetails { get; set; }
        public virtual DbSet<QuestionnaireFeedback> QuestionnaireFeedbacks { get; set; }
        public virtual DbSet<QuestionTitle> QuestionTitles { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SaleLine> SaleLines { get; set; }
        public virtual DbSet<SaleLineService> SaleLineServices { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServicePrice> ServicePrices { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SessionStatu> SessionStatus { get; set; }
        public virtual DbSet<SessionType> SessionTypes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskDocument> TaskDocuments { get; set; }
        public virtual DbSet<TaskStatu> TaskStatus { get; set; }
        public virtual DbSet<TaskType> TaskTypes { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Timer> Timers { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<Trainee> Trainees { get; set; }
        public virtual DbSet<TraineeDocument> TraineeDocuments { get; set; }
        public virtual DbSet<TraineeProgress> TraineeProgresses { get; set; }
        public virtual DbSet<TraineeStatu> TraineeStatus { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<TrainerStatu> TrainerStatus { get; set; }
        public virtual DbSet<TrainingStatu> TrainingStatus { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserDaySlot> UserDaySlots { get; set; }
        public virtual DbSet<UserQuestionnaire> UserQuestionnaires { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
