//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleLineService
    {
        public int Service_ID { get; set; }
        public int AddRemove_ID { get; set; }
        public Nullable<int> Sale_ID { get; set; }
        public int Package_ID { get; set; }
    
        public virtual AddRemove AddRemove { get; set; }
        public virtual Package Package { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Service Service { get; set; }
    }
}
