//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.AuditTrails = new HashSet<AuditTrail>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int Session_ID { get; set; }
        public string Description { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public System.TimeSpan End_Time { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Session_Number { get; set; }
        public byte[] Video { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> Package_ID { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> TimeSlot_ID { get; set; }
        public Nullable<int> SessionType_ID { get; set; }
        public Nullable<int> SessionStatus_ID { get; set; }
        public Nullable<int> Trainee_ID { get; set; }
        public Nullable<int> Practitioner_ID { get; set; }
        public Nullable<int> Trainer_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual Client Client { get; set; }
        public virtual Package Package { get; set; }
        public virtual Practitioner Practitioner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual SessionType SessionType { get; set; }
        public virtual SessionStatu SessionStatu { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
