//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskDocuments = new HashSet<TaskDocument>();
        }
    
        public int Task_ID { get; set; }
        public string Description { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<int> TaskStatus_ID { get; set; }
        public Nullable<int> TaskType_ID { get; set; }
        public Nullable<int> Trainee_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Practitioner_ID { get; set; }
        public Nullable<int> Trainer_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Practitioner Practitioner { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual Trainer Trainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDocument> TaskDocuments { get; set; }
    }
}
