//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDaySlot
    {
        public int UserDaySlot_ID { get; set; }
        public string Name { get; set; }
        public int Practitioner_ID { get; set; }
        public int Trainer_ID { get; set; }
        public int TimeSlot_ID { get; set; }
        public int Date_ID { get; set; }
        public int SessionStatus_ID { get; set; }
        public int Booking_ID { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Date Date { get; set; }
        public virtual Practitioner Practitioner { get; set; }
        public virtual SessionStatu SessionStatu { get; set; }
        public virtual Status Status { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
