//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_FICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuestionnaire
    {
        public int Client_ID { get; set; }
        public int Practitioner_ID { get; set; }
        public int Trainer_ID { get; set; }
        public int Trainee_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Practitioner Practitioner { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
